- README.md
Update README with correct PyTorch Geometric and e3nn version. 
- [ x ] Documentation improvement (updates to user guides, docstrings, or developer docs)
> [hotifx] update pytorch geometric and e3nn versions

- CHANGELOG.md
- README.md
- nequip/data/AtomicData.py
- nequip/data/dataset.py
- nequip/datasets/aspirin.py
- nequip/train/trainer.py
- nequip/utils/initialization.py
- setup.py
torch geometric 1.7 changes some variable names for the Data class. And `num_graph` somehow enter the data.keys, which contaminates some conversion procedures. 
e3nn0.3.2 also update the fully connected layer class attributes, which will break the initializers in configs/minimal.yaml.
close #45 
all current tests passed. (without the pull , it will not work with the latest e3nn and torch_geometric)
> Geometric 1.7.1 compatibility

- CHANGELOG.md
> Fix commands with `pip install`

- README.md
were for outdated version, didn't work for users
credit to @Felipe-Gomez for fix
> Update EMA instructions

- nequip/train/trainer.py
log the version of torch, torch_geometric, e3nn
so the user is aware that we do not support backward/forward compatibility...
> logging the version

- CHANGELOG.md
- configs/full.yaml
- nequip/train/trainer.py
Gradient clipping to replace https://github.com/mir-group/nequip/commit/99c7b2598045ee9ec5db17f2704bc3e67faaba4f.
Basic sanity checks with minimal.yaml.
> Gradient clipping

- CHANGELOG.md
- configs/full.yaml
- configs/minimal_eng.yaml
- nequip/train/_loss.py
- nequip/train/metrics.py
- nequip/utils/config.py
- tests/unit/trainer/test_loss.py
- tests/unit/trainer/test_metrics.py
- tests/unit/trainer/test_trainer.py
allow to use energy/atom for loss function
could be useful for datasets with varying numbers of atoms
unit tests added to tests/unit/train/test_loss module
> Normalize the total energy by natoms

- README.md
- setup.py
Update install instructions after PyG 2.0 update, instruct users to install PyG 1.7.2.
> hotfix pyg 2.0

- CHANGELOG.md
- configs/example.yaml
- configs/full.yaml
- nequip/nn/_atomwise.py
- nequip/train/trainer.py
As the title suggested.
So the naming convention is consistent with the global_rescale. and we can also test on these switches.
> Enable trainable separately for per_species_scale and per_species_shift

- configs/full.yaml
- docs/guide/FAQ.rst
- docs/guide/migrate.rst
- nequip/train/trainer.py
- nequip/utils/git.py
- nequip/utils/regressor.py
- let the device be an input argument for init and yaml
- check the consistency between `model.out_fields` and loss function keywords.
- save git commit versions of e3nn, nequip, and torch_runstats
Easier changing of devices. Better safe guard against wrong set up of loss function / model.
> Update trainer logging and sanity checks

- README.md
As suggested by @goxeq  at #103 
close #103
> Update Readme.md to 1.7.2 torch_geometric

- configs/full.yaml
- nequip/utils/regressor.py
- tests/unit/data/test_dataset.py
Add a stride argument to use less data for GP fitting.
Resolves: #???
> Add stride arguments to GP fit

- nequip/model/_scaling.py
- nequip/nn/_atomwise.py
- nequip/utils/regressor.py
allow to turn off scales or shifts for per species scaling.
> Bugfix null option for per_species_rescale

- CHANGELOG.md
- configs/example.yaml
- configs/full.yaml
- configs/minimal.yaml
- nequip/model/__init__.py
- nequip/model/_build.py
- nequip/model/_eng.py
- nequip/model/builder_utils.py
- tests/unit/model/test_builder_utils.py
- tests/unit/model/test_eng_force.py
> Automatic `avg_num_neighbors`

- nequip/data/_keys.py
- nequip/model/__init__.py
- nequip/model/_grads.py
- nequip/nn/__init__.py
- nequip/nn/_grad_output.py
- tests/unit/model/test_eng_force.py
Module to compute partial forces.
Added tests
- [ X ] New feature (non-breaking change which adds or improves functionality)
> Partial forces

- CHANGELOG.md
- configs/example.yaml
- configs/full.yaml
- configs/minimal.yaml
- configs/minimal_eng.yaml
- docs/options/dataset.rst
- nequip/data/dataset.py
- nequip/data/transforms.py
- tests/unit/model/test_eng_force.py
Simpler specification of chemical symbols.
> Chemical symbols

- configs/full.yaml
Validation_* should be lowercase now.
> validation_* lowercase

- CHANGELOG.md
- configs/full.yaml
- nequip/train/trainer_wandb.py
tested with real wandb account, `example.yaml`, and a restart
> wandb.watch

- nequip/model/_eng.py
Let SimpleIrrepsConfig builder to consider prefix while converting simple irreps to real irreps.
> change the prefix to autodetection

- nequip/train/trainer.py
Previous pull #141  has a bug in the training condition. The only the outer layer unscale will be run to get the normalized target for loss function calculation.
> bugfix for multi-rescale-layer model training

- nequip/scripts/benchmark.py
- nequip/scripts/deploy.py
- nequip/scripts/evaluate.py
- nequip/scripts/train.py
- nequip/train/trainer.py
- nequip/utils/git.py
- nequip/utils/versions.py
save code version in training script instead of in the trainer.
Store the code versions at the very beginning of the training code, so that the data is uploaded to `wandb`.
> save code version in training script

- CHANGELOG.md
- configs/example.yaml
- configs/full.yaml
- nequip/scripts/evaluate.py
Updated example.yaml + full.yaml with better defaults + comments
Change metrics defaults to total F-MAE/F-RMSE, larger max_epochs and provide better comments. 
* Old comments had still proposed a 100:1 F:E weighting
* Old metrics were per-species F-MAE
- [x ] I have updated `CHANGELOG.md`.
- [ x] I have updated the documentation (if relevant).
> Updated example.yaml + full.yaml with better defaults + comments

- tests/unit/data/test_dataset.py
- tests/unit/utils/test_gp.py
Try to make the unit test on linear regression stable
Resolves: #???
> Test linear regression

- .flake8
- .github/workflows/lint.yaml
- .github/workflows/tests.yml
- .github/workflows/tests_develop.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- nequip/ase/nosehoover.py
- nequip/nn/_interaction_block.py
- nequip/utils/regressor.py
- nequip/utils/savenload.py
I started using nequip recently with great results. 
This PR does not include any changes to the Code but adds:
-  a [pre-commit](https://pre-commit.com/) hook.
-  updated CI to test for black / flake8.
- testing black and flake8 now uses an image.
-  `.flake8` config file based on `CONTRIBUTING.md`.
I found myself adding these when looking into the nequip code and wanted to share them.
I use a similar setup myself. The only difference is that I'm also using the https://github.com/PyCQA/isort package in addition.
> Add `pre-commit` hook + Add black to CI

- CHANGELOG.md
- nequip/data/dataset.py
- nequip/scripts/benchmark.py
- nequip/scripts/deploy.py
- nequip/scripts/evaluate.py
- nequip/scripts/train.py
- nequip/utils/_global_options.py
- nequip/utils/multiprocessing.py
- tests/conftest.py
> Ase multiprocess

- configs/example.yaml
> Better example.yaml defaults

- configs/example.yaml
- configs/full.yaml
Adam -> AMSGrad based on findings.
> Fix optimizer defaults

- docs/guide/troubleshoot.md
Added description help with compilation errors for nequip-compile.
I just added more explanation/context about issues one might have when using nequip-compile.
Because I had trouble with using nequip-compile on FRONTIER. 
By updating my GCC to a version that supports C++17 my allegro model compiled successfully.
> Update troubleshoot.md to include more information about nequip-compile

- docs/guide/accelerations/openequivariance.md
Same as the other PR for Allegro with CuEq
> Explicitly copy in OeQ model load error
