mir-group/nequip

CHANGELOG.md
configs/full.yaml
nequip/nn/_convnetlayer.py
nequip/utils/wandb.py
tests/model/test_eng_force.py

Fix specifying nonlinenarities with `wandb` is enabled.
Disallows use of non-string configuration keys, even in nested dicts.
`minimal.yaml` training runs; test suite.

Fix config of nonlinearities with wandb

---

CHANGELOG.md
README.md
configs/full.yaml
examples/monkeypatch.py
nequip/data/dataset.py
nequip/scripts/evaluate.py
nequip/scripts/restart.py
nequip/scripts/train.py
nequip/train/trainer.py
nequip/utils/auto_init.py
tests/unit/data/test_dataset.py
tests/unit/datasets/test_simplesets.py

Option to specify a completely different dataset to sample validation set from. By default behavior of sampling both from one dataset in non-overlapping way is maintained.
Avoid lots of wasted time calling `nequip-evaluate` during some trainings.
Existing unit tests pass, should write new ones.

Separate validation set option

---

nequip/train/trainer.py

Remove the typo for the stop_arg in Trainer

Hot fix for the early stopping typo

---

CHANGELOG.md
nequip/nn/_graph_mixin.py
tests/unit/nn/test_sequential.py

as described above
So we can insert to the network sequence based on the before/after module name
in tests/unit/nn/test_sequential, a parameter is added to the test_insert function to test out both options.

Add before option to the SequentialGraphNetwork insert method

---

CHANGELOG.md
configs/example.yaml
configs/full.yaml
nequip/data/AtomicData.py
nequip/data/_build.py
nequip/model/_scaling.py
nequip/train/_key.py
nequip/train/_loss.py
nequip/train/trainer.py
nequip/utils/__init__.py
nequip/utils/auto_init.py
tests/integration/test_train.py

- Change default `metrics_key` from `loss` to `validation_loss`.
- Allow users to  register new `node_fields`, `graph_fields` and `edge_fields` via yaml interface
- allow `global_rescale` and `per_species_rescale` prefixes to be removed in the yaml file.
- a new `get_w_prefix` method is available to search of variables among dictionary.
The current development version fails to restart due to a conflict on the `metrics_key`.
And it only takes `dataset_node_fields`, but not `node_fields`.

Fix requeue mode on develop branch

---

README.md
setup.py

- note current lack of support for PyTorch 1.10
- force `main` to use e3nn versions before the 0.4.0 breaking changes

version updates for dependencies

---

nequip/nn/_graph_mixin.py

Add a function `add_independent_irreps` to GraphMixin class in order to let new irreps from inserted layers propagate in the SequentialGraphNetwork model.

handle the irreps for SequentialGraphNetwork.insert

---

CHANGELOG.md
nequip/model/_scaling.py
nequip/nn/_atomwise.py
nequip/nn/_graph_mixin.py
nequip/nn/_rescale.py
nequip/train/trainer.py

Current implementation only allows one final rescale layer with one constant. This pull enable multiple rescale layers
Should be merged to develop after #139 
- assume all the rescale layers are at the outermost part of the model
- trainer go through all rescale layers for scale/unscale
- rescale module added a new argument `related_keys` to make sure only related `callback` functions are called.
Resolves: #???

Enable multiple layers of rescale

---

nequip/data/dataset.py
tests/unit/data/test_dataset.py

When subdataset is used (`self._indices is not None`), Dataset Statistics will sample configurations from the subdataset instead of the whole dataset. However, the graph_selector follows the same order in `self._indices` while the node_selector sorts the graph_selector and then augments to the node. That's why they have different orders.
This will lead to wrong `per_species` statistics.

:bug: bugfix to match the order between graph_selector and node selector in dataset statistics

---

nequip/model/_scaling.py
nequip/train/trainer.py

:bug: Bugfix rescale key list introduced by the multilayer pull

---

configs/full.yaml
nequip/train/trainer.py

Record cumulative wall time in the trainer dictionary.
So the early stopping works consistently no matter whether the job is restarted or started fresh.

record cumulative wall time in Trainer

---

CHANGELOG.md
nequip/data/AtomicData.py
nequip/train/trainer.py

In the NPZ dataset, the keys in `key_mapping` are automatically added to the include_keys. But it is not the case in the case dataset. 
The from_ase function is slightly modified to make the ase dataset and npz dataset perform consistently.

add mapped keys to include keys for ase dataset

---

nequip/model/_scaling.py

Make dataset an optional argument for rescaling builders. so one can define the model from python api without errors like below
```python
from nequip.utils import Config
from nequip.model import model_from_config
from nequip.scripts.train import default_config
config = {}
config.update(default_config)
config.update(dict(
l_max=2,
parity=True,
num_features=64,
avg_num_neighbors=None,
chemical_symbols = ["H", "C", "O"],
num_basis=8,
r_max=4.0,
per_species_rescale_scales_trainable = True,
per_species_rescale_shifts_trainable = False,
global_rescale_scale = 1.0,
per_species_rescale_shifts = 0.0,
per_species_rescale_scales = 1.0,
))
final_model = model_from_config(
config=Config.from_dict(config), initialize=True, dataset=None,
)
```

make dataset an optional argument for rescaling builder

---

CITATION.cff
README.md
docs/cite.rst
examples/plot_dimers.py

This PR includes a few minor cosmetic updates:
- Adds a `CITATION.cff` file to the NequIP repo (Misc project target for `nequip-dev`)
- Updates the `README` and citation page on the docs (previously empty)
- Some cleanup and fixes for the `plot_dimers.py` example script (had some accidental hard-set parameters etc)
- Avoids accidental `""Do NOT manually set PYTORCH_JIT_USE_NNC_NOT_NVFUSER=0..."` warning calls when `PYTORCH_JIT_USE_NNC_NOT_NVFUSER` in `os.environ` (but not set to 0)

Minor Fixes

---

nequip/train/trainer_wandb.py

Add import of torch.distributed in trainer_wandb.py
The import is missing and breaks nequip-train when wandb is enabled.
The change works for my training with DDP and wandb enabled.

add missing torch.distributed import

---

.github/workflows/tests.yml
.github/workflows/tests_develop.yml

GH actions for https://github.com/mir-group/nequip/pull/465 seems to be failing, testing if adding a torch version bound helps.

Bound CI torch version

---

nequip/train/early_stopping.py

I greatly appreciated your paper :)
While working with your code, I think I found a small but nevertheless consequential typo in your early stopping procedure,
than kept my runs from finishing.

fix sign error in early_stopping.py

---

nequip/train/_loss.py

This is the customized upstream fix for allegro-pol missing loss module. 
See https://github.com/mir-group/allegro-pol/pull/3 for detials.
This PR makes loss object construction more robust to make sure the example [config BaTiO3.yaml](https://github.com/mir-group/allegro-pol/blob/631de869fca91bdfc62f28df775cb01922eb1ef4/configs/BaTiO3.yaml) is runnable.
After this fix, `nequip-train configs/BaTiO3.yaml` can be executed without any problem.

Allegro-pol fix

---

nequip/train/callbacks/wandb_watch.py

Fixes a minor typo in the wandb watch callback, where the docstrings used `log_type` but code used `log` -- the latter is better as it matches the pytorch lightning nomenclature for this

Minor typo fix in wandb watch callback

---

nequip/scripts/compile.py
nequip/utils/aot.py

This adds a `--skip-dtype-check` option to `nequip-compile` to skip the dtype similarity checks at the end of model compilation.
The motivation for this is that, when compiling on CPU at least, `test_model_output_similarity_by_dtype` spikes the memory demand. This prevents the use of `nequip-compile` on FasRC login nodes (which annoyingly have quite a low amount of RAM) due to OOM, which makes things a little bit awkward. Using this option, `nequip-compile` can run on the login nodes. Intended only really for power users / developers, when one is already confident there are no dtype issues with the models.

Allow model check to be skipped with `nequip-compile` via env var

---

nequip/train/callbacks/wandb_watch.py

This is a small fix for handling the `log` setting for the `WandbWatch` callback. 
`log` is one of the input parameters for the `watch()` method, but should not be stored under `self.log` in the callback as this interferes with the `LightningModule.log()` method and causes failures. This PR changes the `log` setting to be stored under `self.wandb_log_setting`, along with a comment noting why this is. Tested and works well like this.

`wandb.watch()` callback fix

---

nequip/data/dataset/lmdb_dataset.py

Feel free to close if this isn't wanted.
Just a drop-in addition for an `exclude_keys` option with `NequIPLMDBDataset` (useful if dealing with massive LMDB datasets where re-processing to remove certain keys can take a while). 
Tested and worked well for me.

Add `exclude_keys` option to `NequIPLMDBDataset `
